export const menu = [
    {
        id: 1,
        title: "CHÍNH",
        listItems: [
            {
                id: 1,
                title: "Trang Chủ",
                url: "/",
                icon: "home.svg",
            },
            {
                id: 2,
                title: "Hồ Sơ",
                url: "/users/1",
                icon: "user.svg",
            },
        ],
    },
    {
        id: 2,
        title: "DANH SÁCH",
        listItems: [
            {
                id: 1,
                title: "Người dùng",
                url: "/users",
                icon: "user.svg",
            },
            {
                id: 2,
                title: "Sản Phẩm",
                url: "/products",
                icon: "product.svg",
            },
            {
                id: 3,
                title: "Đặt Hàng",
                url: "/",
                icon: "order.svg",
            },
            {
                id: 4,
                title: "Bài Đăng",
                url: "/",
                icon: "post.svg",
            },
        ],
    },
    {
        id: 3,
        title: "Tổng Quan",
        listItems: [
            {
                id: 1,
                title: "Thành Phần",
                url: "/",
                icon: "element.svg",
            },
            {
                id: 2,
                title: "Ghi Chú",
                url: "/",
                icon: "note.svg",
            },
            {
                id: 3,
                title: "Hình Thức",
                url: "/",
                icon: "form.svg",
            },
            {
                id: 4,
                title: "Lịch Trình",
                url: "/",
                icon: "calendar.svg",
            },
        ],
    },
    {
        id: 4,
        title: "Bảo Trì",
        listItems: [
            {
                id: 1,
                title: "Cài Đặt",
                url: "/",
                icon: "setting.svg",
            },
            {
                id: 2,
                title: "Sao Lưu",
                url: "/",
                icon: "backup.svg",
            },
        ],
    },
    {
        id: 5,
        title: "Phân Tích",
        listItems: [
            {
                id: 1,
                title: "Biểu Đồ",
                url: "/",
                icon: "chart.svg",
            },
            {
                id: 2,
                title: "Nhật Ký",
                url: "/",
                icon: "log.svg",
            },
        ],
    },
];

export const topDealUsers = [
    {
        id: 1,
        img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        username: "Hồ Chí Nhân",
        email: "hochinhan5612@gmail.com",
        amount: "3.668",
    },
    {
        id: 2,
        img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username: "Đỗ Kim Lâm",
        email: "belamdepzai@gmail.com",
        amount: "3.256",
    },
    {
        id: 3,
        img: "https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username: "Nguyễn Đức Thiệp",
        email: "ducthiepngu@gmail.com",
        amount: "2.998",
    },
    {
        id: 4,
        img: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username: "Nguyễn Minh Tiến",
        email: "minhtien2003@gmail.com",
        amount: "2.512",
    },
    {
        id: 5,
        img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username: "Đinh Thanh Tân",
        email: "tandinh5508@gmail.com",
        amount: "2.134",
    },
    {
        id: 6,
        img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username: "Trần Thị Thanh",
        email: "thanhthanh1012@gmail.com",
        amount: "1.932",
    },
    {
        id: 7,
        img: "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=1600",
        username: "Nguyễn Văn Bạch",
        email: "bachbach5555@gmail.com",
        amount: "1.560",
    },
];

export const chartBoxUser = {
    color: "#8884d8",
    icon: "/userIcon.svg",
    title: "Người Dùng",
    number: "11.238",
    dataKey: "người dùng",
    percentage: 45,
    chartData: [
        { name: "Chủ Nhật", "người dùng": 400 },
        { name: "Thứ Hai", "người dùng": 600 },
        { name: "Thứ Ba", "người dùng": 500 },
        { name: "Thứ Tư", "người dùng": 700 },
        { name: "Thứ Năm", "người dùng": 400 },
        { name: "Thứ Sáu", "người dùng": 500 },
        { name: "Thứ Bảy", "người dùng": 450 },
    ],
};

export const chartBoxProduct = {
    color: "skyblue",
    icon: "/productIcon.svg",
    title: "Sản Phẩm",
    number: "238",
    dataKey: "sản phẩm",
    percentage: 21,
    chartData: [
        { name: "Chủ NhậT", "sản phẩm": 400 },
        { name: "Thứ Hai", "sản phẩm": 600 },
        { name: "Thứ Ba", "sản phẩm": 500 },
        { name: "Thứ Tư", "sản phẩm": 700 },
        { name: "Thứ Năm", "sản phẩm": 400 },
        { name: "Thứ Sáu", "sản phẩm": 500 },
        { name: "Thứ Bảy", "sản phẩm": 450 },
    ],
};
export const chartBoxRevenue = {
    color: "teal",
    icon: "/revenueIcon.svg",
    title: "Doanh Thu",
    number: "$56.432",
    dataKey: "doanh thu",
    percentage: -12,
    chartData: [
        { name: "Chủ Nhật", "doanh thu": 400 },
        { name: "Thứ Hai", "doanh thu": 600 },
        { name: "Thứ Ba", "doanh thu": 500 },
        { name: "Thứ Tư", "doanh thu": 700 },
        { name: "Thứ Năm", "doanh thu": 400 },
        { name: "Thứ Sáu", "doanh thu": 500 },
        { name: "Thứ Bảy", "doanh thu": 450 },
    ],
};
export const chartBoxConversion = {
    color: "gold",
    icon: "/conversionIcon.svg",
    title: "Đơn Hàng",
    number: "2.6",
    dataKey: "đơn hàng",
    percentage: 12,
    chartData: [
        { name: "Chủ Nhật", "đơn hàng": 400 },
        { name: "Thứ Hai", "đơn hàng": 600 },
        { name: "Thứ Ba", "đơn hàng": 500 },
        { name: "Thứ Tư", "đơn hàng": 700 },
        { name: "Thứ Năm", "đơn hàng": 400 },
        { name: "Thứ Sáu", "đơn hàng": 500 },
        { name: "Thứ Bảy", "đơn hàng": 450 },
    ],
};

export const barChartBoxRevenue = {
    title: "LỢI NHUẬN KIẾM ĐƯỢC",
    color: "#8884d8",
    dataKey: "lợi nhuận",
    chartData: [
        {
            name: "Chủ Nhật",
            "lợi nhuận": 4000,
        },
        {
            name: "Thứ Hai",
            "lợi nhuận": 3000,
        },
        {
            name: "Thứ Ba",
            "lợi nhuận": 2000,
        },
        {
            name: "Thứ Tư",
            "lợi nhuận": 2780,
        },
        {
            name: "Thứ Năm",
            "lợi nhuận": 1890,
        },
        {
            name: "Thứ Sáu",
            "lợi nhuận": 2390,
        },
        {
            name: "Thứ Bảy",
            "lợi nhuận": 3490,
        },
    ],
};

export const barChartBoxVisit = {
    title: "TỔNG LƯỢT TRUY CẬP",
    color: "#FF8042",
    dataKey: "truy cập",
    chartData: [
        {
            name: "Chủ Nhật",
            "truy cập": 4000,
        },
        {
            name: "Thứ Hai",
            "truy cập": 3000,
        },
        {
            name: "Thứ Ba",
            "truy cập": 2000,
        },
        {
            name: "Thứ Tư",
            "truy cập": 2780,
        },
        {
            name: "Thứ Năm",
            "truy cập": 1890,
        },
        {
            name: "Thứ Sáu",
            "truy cập": 2390,
        },
        {
            name: "Thứ Bảy",
            "truy cập": 3490,
        },
    ],
};

export const userRows = [
    {
        id: 1,
        img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        lastName: "Nhân",
        firstName: "Hồ Chí",
        email: "hochinhan5612@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 2,
        img: "https://images.pexels.com/photos/1181519/pexels-photo-1181519.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Manning",
        firstName: "Stella",
        email: "comhuhmit@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 3,
        img: "https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Greer",
        firstName: "Mary",
        email: "ujudokon@hottmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 4,
        img: "https://images.pexels.com/photos/871495/pexels-photo-871495.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Williamson",
        firstName: "Mildred",
        email: "tinhavabe@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 5,
        img: "https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Gross",
        firstName: "Jose",
        email: "gobtagbes@yahoo.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
    },
    {
        id: 6,
        img: "https://images.pexels.com/photos/769745/pexels-photo-769745.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Sharp",
        firstName: "Jeremy",
        email: "vulca.eder@mail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 7,
        img: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Lowe",
        firstName: "Christina",
        email: "reso.bilic@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
    },
    {
        id: 8,
        img: "https://images.pexels.com/photos/428364/pexels-photo-428364.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Dean",
        firstName: "Garrett",
        email: "codaic@mail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 9,
        img: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Parsons",
        firstName: "Leah",
        email: "uzozor@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
    },
    {
        id: 10,
        img: "https://images.pexels.com/photos/775358/pexels-photo-775358.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Reid",
        firstName: "Elnora",
        email: "tuhkabapu@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 11,
        img: "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Dunn",
        firstName: "Gertrude",
        email: "gibo@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
        verified: true,
    },
    {
        id: 12,
        img: "https://images.pexels.com/photos/774095/pexels-photo-774095.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Williams",
        firstName: "Mark",
        email: "tic.harvey@hotmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
    },
    {
        id: 13,
        img: "https://images.pexels.com/photos/761977/pexels-photo-761977.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Cruz",
        firstName: "Charlotte",
        email: "ceuc@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
    },
    {
        id: 14,
        img: "https://images.pexels.com/photos/927022/pexels-photo-927022.jpeg?auto=compress&cs=tinysrgb&w=1600",
        lastName: "Harper",
        firstName: "Sara",
        email: "bafuv@hotmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
    },
    {
        id: 15,
        img: "https://images.pexels.com/photos/8405873/pexels-photo-8405873.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
        lastName: "Griffin",
        firstName: "Eric",
        email: "ubi@gmail.com",
        phone: "123 456 789",
        createdAt: "01.02.2023",
    },
];

export const products = [
    {
        id: 1,
        img: "https://store.sony.com.au/on/demandware.static/-/Sites-sony-master-catalog/default/dw1b537bbb/images/PLAYSTATION5W/PLAYSTATION5W.png",
        title: "Playstation 5 Digital Edition",
        color: "white",
        producer: "Sony",
        price: "25.000.000 VNĐ",
        createdAt: "01.02.2023",
        inStock: true,
    },
    {
        id: 2,
        img: "https://www.pngmart.com/files/6/Dell-Laptop-PNG-Image.png",
        title: "Dell Laptop KR211822",
        color: "black",
        producer: "Dell",
        price: "20.000.000 VNĐ",
        createdAt: "01.02.2023",
        inStock: true,
    },
    {
        id: 3,
        img: "http://images.samsung.com/is/image/samsung/uk-led-tv-hg40ed670ck-hg40ed670ckxxu-001-front",
        title: "Samsung TV 4K SmartTV",
        color: "gray",
        producer: "Samsung",
        price: "50.000.000 VNĐ",
        createdAt: "01.02.2023",
        inStock: true,
    },
    {
        id: 4,
        img: "https://raylo.imgix.net/iphone-14-blue.png",
        title: "Apple Iphone 14 Pro Max",
        color: "white",
        producer: "Apple",
        price: "30.000.000 VNĐ",
        createdAt: "01.02.2023",
        inStock: true,
    },
    {
        id: 5,
        img: "https://www.signify.com/b-dam/signify/en-aa/about/news/2020/20200903-movie-night-essentials-popcorn-ice-cream-and-the-new-philips-hue-play-gradient-lightstrip/packaging-lighstrip.png",
        title: "Philips Hue Play Gradient",
        color: "rainbow",
        producer: "Philips",
        price: "45.000.000 VNĐ",
        createdAt: "01.02.2023",
    },
    {
        id: 6,
        img: "https://www.smartworld.it/wp-content/uploads/2019/09/High_Resolution_PNG-MX-Master-3-LEFT-GRAPHITE.png",
        title: "Logitech MX Master 3",
        color: "black",
        producer: "Logitech",
        price: "10.000.000 VNĐ",
        createdAt: "01.02.2023",
        inStock: true,
    },
    {
        id: 7,
        img: "https://www.pngarts.com/files/7/Podcast-Mic-PNG-Picture.png",
        title: "Rode Podcast Microphone",
        color: "gray",
        producer: "Rode",
        price: "10.000.000 VNĐ",
        createdAt: "01.02.2023",
    },
    {
        id: 8,
        img: "https://5.imimg.com/data5/SW/VM/MY-5774620/toshiba-split-ac-2-ton-3-star-rated-ras-24s3ks-500x500.png",
        title: "Toshiba Split AC 2",
        color: "white",
        producer: "Toshiba",
        price: "10.000.000 VNĐ",
        createdAt: "01.02.2023",
        inStock: true,
    },
    {
        id: 9,
        img: "https://img.productz.com/review_image/102489/preview_sony-kdl-50w800b-50-inch-hdtv-review-superb-picture-102489.png",
        title: "Sony Bravia KDL-47W805A",
        color: "black",
        producer: "Sony",
        price: "10.000.000 VNĐ",
        createdAt: "01.02.2023",
    },
    {
        id: 10,
        img: "https://venturebeat.com/wp-content/uploads/2015/07/As_AO1-131_gray_nonglare_win10_03.png?fit=1338%2C1055&strip=all",
        title: "Acer Laptop 16 KL-4804",
        color: "black",
        producer: "Acer",
        price: "10.000.000 VNĐ",
        createdAt: "01.02.2023",
        inStock: true,
    },
    {
        id: 11,
        img: "https://img.productz.com/review_image/102489/preview_sony-kdl-50w800b-50-inch-hdtv-review-superb-picture-102489.png",
        title: "Sony Bravia KDL-47W805A",
        color: "black",
        producer: "Sony",
        price: "10.000.000 VNĐ",
        createdAt: "01.02.2023",
    },
    {
        id: 12,
        img: "https://venturebeat.com/wp-content/uploads/2015/07/As_AO1-131_gray_nonglare_win10_03.png?fit=1338%2C1055&strip=all",
        title: "Acer Laptop 16 KL-4804",
        color: "black",
        producer: "Acer",
        price: "10.000.000 VNĐ",
        createdAt: "01.02.2023",
        inStock: true,
    },
];

export const singleUser = {
    id: 1,
    title: "Seven Coder",
    img: "https://images.pexels.com/photos/17397364/pexels-photo-17397364.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    info: {
        username: "SevenCoder",
        fullname: "Hồ Chí Nhân",
        email: "hochinhan5612@gmail.com",
        phone: "123 456 789",
        status: "verified",
    },
    chart: {
        dataKeys: [
            { name: "truy cập", color: "#82ca9d" },
            { name: "tương tác", color: "#8884d8" },
        ],
        data: [
            {
                name: "Chủ Nhật",
                "truy cập": 4000,
                "tương tác": 2400,
            },
            {
                name: "Hai",
                "truy cập": 3000,
                "tương tác": 1398,
            },
            {
                name: "Ba",
                "truy cập": 2000,
                "tương tác": 3800,
            },
            {
                name: "Tư",
                "truy cập": 2780,
                "tương tác": 3908,
            },
            {
                name: "Năm",
                "truy cập": 1890,
                "tương tác": 4800,
            },
            {
                name: "Sáu",
                "truy cập": 2390,
                "tương tác": 3800,
            },
            {
                name: "Bảy",
                "truy cập": 3490,
                "tương tác": 4300,
            },
        ],
    },
    activities: [
        {
            text: "SevenCoder đã mua Playstation 5 Digital Edition",
            time: "3 ngày trước",
        },
        {
            text: "SevenCoder thêm 3 sản phẩm vào danh sách yêu thích",
            time: "1 tuần trước",
        },
        {
            text: "SevenCoder đã mua Sony Bravia KD-32w800",
            time: "2 tuần trước",
        },
        {
            text: "SevenCoder bình luận sản phẩm",
            time: "1 tháng trước",
        },
        {
            text: "SevenCoder thêm 1 sản phẩm vào danh sách yêu thích",
            time: "1 tháng trước",
        },
        {
            text: "SevenCoder bình luận sản phẩm",
            time: "2 tháng trước",
        },
    ],
};
export const singleProduct = {
    id: 1,
    title: "Playstation 5 Digital Edition",
    img: "https://store.sony.com.au/on/demandware.static/-/Sites-sony-master-catalog/default/dw1b537bbb/images/PLAYSTATION5W/PLAYSTATION5W.png",
    info: {
        productId: "Ps5SDF1156d",
        color: "white",
        price: "25.000.000",
        producer: "Sony",
        export: "Japan",
    },
    chart: {
        dataKeys: [
            { name: "truy cập", color: "#82ca9d" },
            { name: "đặt hàng", color: "#8884d8" },
        ],
        data: [
            {
                name: "Chủ Nhật",
                "truy cập": 4000,
                "đặt hàng": 2400,
            },
            {
                name: "Hai",
                "truy cập": 3000,
                "đặt hàng": 1398,
            },
            {
                name: "Ba",
                "truy cập": 2000,
                "đặt hàng": 3800,
            },
            {
                name: "Tư",
                "truy cập": 2780,
                "đặt hàng": 3908,
            },
            {
                name: "Năm",
                "truy cập": 1890,
                "đặt hàng": 4800,
            },
            {
                name: "Sáu",
                "truy cập": 2390,
                "đặt hàng": 3800,
            },
            {
                name: "Bảy",
                "truy cập": 3490,
                "đặt hàng": 4300,
            },
        ],
    },
    activities: [
        {
            text: "SevenCoder đã mua Playstation 5 Digital Edition",
            time: "3 ngày trước",
        },
        {
            text: "SevenCoder đã thêm Playstation 5 Digital Edition vào danh sách yêu thích",
            time: "1 tuần trước",
        },
        {
            text: "TankDink đã mua Playstation 5 Digital Edition",
            time: "2 tuần trước",
        },
        {
            text: "KimLam đã bình luận về sản phẩm",
            time: "1 tháng trước",
        },
        {
            text: "DucThiep đã thêm Playstation 5 Digital Edition vào danh sách yêu thích",
            time: "1 tháng trước",
        },
        {
            text: "ToAnh đã bình luận về sản phẩm",
            time: "2 tháng trước",
        },
    ],
};
